config/routes.rb
Rails.application.routes.draw do
  get 'responses/index'
  resources :users, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'users/profile'
  get 'top/main'
  root 'top#login'
  root 'top#main'
  post 'top/login'
  get 'top/login'
  get 'top/logout'
  resources :thres
  post '/thres/search', to: 'thres#search'
  resources :responses
  resources :likes
  resources :dislikes
  get '/get_image/:id', to: 'responses#get_image'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
end

app/models/dislike.rb
class Dislike < ApplicationRecord
    belongs_to :user
    belongs_to :response
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :response
end

app/models/response.rb
class Response < ApplicationRecord
    has_one_attached :image
    validates :message, length:{maximum: 300}
    has_many :likes
    has_many :dislikes
    has_many :users
    has_many :like_users, through: :likes, source: :user
    has_many :dislike_users, through: :dislikes, source: :user
end

app/models/thre.rb
class Thre < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    validates :uid, :name, presence: true, uniqueness: true
    validates :pass, presence: true, length: { minimum: 8 }
    has_many :likes
    has_many :dislikes
    has_many :responses
    has_many :like_responses, through: :likes, source: :response
    has_many :dislike_responses, through: :dislikes, source: :response
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user
        if session[:login_uid]
            User.find_by(uid: session[:login_uid])
        end
    end
    helper_method :current_user
    
    
end

app/controllers/dislikes_controller.rb
class DislikesController < ApplicationController
    def create
        res = Response.find(params[:res_id])
        user = User.find_by(uid: session[:login_uid])
        user.dislike_responses << res
        redirect_to responses_path
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        res = Response.find(params[:res_id])
        user = User.find_by(uid: session[:login_uid])
        user.like_responses << res
        redirect_to responses_path
    end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def index
    @responses = Response.all
    @count = 0
    @thre_id = params[:thre_id]
  end
  
  def new
    @response = Response.new
  end
  
  def create
    user = User.find_by(uid: current_user.uid)
    @response = Response.new(message: params[:response][:message], user_id: user.uid, thre_id: params[:response][:thre_id], tdate: Time.current)
    if image = params[:response][:image]
      @response.image.attach(image)
    end

    if @response.save
      redirect_to thre_path(current_user.id) #"/**"
    else
      render 'new'
    end
  end
  
  def destroy
    response = Response.find(params[:id])
    response.destroy
    redirect_to thre_path(current_user.id)
  end
  
  def show
    @response = Response.find(params[:id])
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def index
  end
end

app/controllers/thres_controller.rb
class ThresController < ApplicationController
  def index
    @thres = Thre.all
  end
  
  def new
    @thre = Thre.new
  end
  
  def show
    @responses = Response.all
  end
  
  def create
    @thre = Thre.new(title: params[:thre][:title], user_id: params[:thre][:user_id], t_date: Time.current)
    if @thre.save
      redirect_to thres_path #"/**"
    else
      render 'new'
    end
  end
  
  def destroy
    thre = Thre.find(params[:id])
    thre.destroy
    redirect_to thres_path
  end
  
  def edit
    @thre = Thre.find(params[:id])
  end
  
  def update
    thre = Thre.find(params[:id])
    thre.update(title: params[:thre][:title], t_date: Time.current)
    redirect_to thres_path
  end
  
  def search
    @thres = Thre.where('title LIKE(?)', "%#{params[:keyword]}%")
    render "index"
  end
  
  def show
    @thre = Thre.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    if session[:login_uid]
        render "main"
    else
        render "login"
    end
  end
  
  def login
    input_pass = params[:pass]
    if User.find_by(uid: params[:uid])
        user = User.find_by(uid: params[:uid])
        db_pass = user.pass
        if BCrypt::Password.new(db_pass) == input_pass
            session[:login_uid] = params[:uid]
            render top_main_path
        else
            redirect_to root_path
        end
    end
  end

  def logout
      session.delete(:uid)
      redirect_to top_login_path
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(uid: params[:user][:uid], pass: params[:user][:pass], name: params[:user][:name])
    if @user.save
      if @user.update(pass: BCrypt::Password.create(@user.pass))
        @user.save
        redirect_to users_path #"/**"
      else
        @user.destroy
        render 'new'
      end
    else
      render 'new'
    end
  end
  
  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    user = User.find(params[:id])
    user.update(name: params[:user][:name])
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dislikes_helper.rb
module DislikesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/thres_helper.rb
module ThresHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/responses/index.html.erb
<% @responses.each do |res| %>
    <% Response.where(user_id: current_user.uid).each do |res| %>
   <p> 
       <%= @count = @count + 1 %>：
       <%= res.tdate.strftime("%Y/%m/%d %X") %>
       <%= link_to '表示', response_path(res.id) %>
       <%= link_to '削除', response_path(res.id), method: :delete %>
    </p>
    <p>
       <%= res.message %>
    </p>
    <p>
       <% if res.image.attached? %>
           <%= image_tag res.image, width: '10%', height: '10%'  %>
       <% else %>
           <%= image_tag 'n.png', width: '0%', height: '0%' %>
       <% end %>
    </p>
    <% end %>
<% end %>
<%= params[:id] %>
<p><%= link_to 'レスの追加', new_response_path(id: params[:id]) %></p>
<p><%= link_to 'スレに戻る', thres_path %></p>
<p><%= link_to 'トップに戻る', top_main_path %></p>

app/views/responses/new.html.erb
<p>
<%= form_for @response , url: {action: :create} do |f| %>
    <%= f.label :message, 'メッセージ' %>
    <%= f.text_field :message %>
    <%= f.label :image, '画像' %>
    <%= f.file_field :image, accept: :image %>
    <%= f.submit '投稿する' %>
<% end %>
</p>

app/views/responses/show.html.erb
<p>
    <%= @response.tdate.strftime("%Y/%m/%d %X") %>
</p>
<p>
    <%= @response.message %>
</p>
<p>
    <% if @response.image.attached? %>
        <%= image_tag @response.image %>
    <% else %>
        <%= image_tag 'n.png', width: '0%', height: '0%' %>
    <% end %>
</p>
<p><%= link_to '戻る', thre_path(current_user.id) %></p>

app/views/scores/index.html.erb
<h1>評価機能　#テスト中</h1>
<p>Find me in app/views/scores/index.html.erb</p>

app/views/thres/edit.html.erb
<%= form_for @thre, url: {action: :update} do |f| %>
    <%= f.label :title, 'タイトル' %>
    <%= f.text_area :title%>
    <%= f.submit '更新' %>
<%end%>

app/views/thres/index.html.erb
<div class = thr>
    <h1>スレ一覧</h1>
    <p></p>
    <%= form_tag thres_search_path, method: :post do %>
        <%= label_tag 'キーワード' %>
        <%= text_field_tag :keyword %>
        <%= submit_tag '検索' %>
    <% end %>
    <% @thres.each do |my| %>
       <p> 
           <strong><%= my.title %></strong>
           <%= my.t_date.strftime("%Y/%m/%d") %>
           <%= link_to '閲覧', thre_path(my.id)%>
           <%= link_to '削除', thre_path(my.id), method: :delete %>
           <%= link_to '編集', edit_thre_path(my.id) %>
        </p>
    <% end %>

    <p><%= link_to '新規追加', new_thre_path %></p>
    <p><%= link_to 'トップに戻る', top_main_path %></p>
</div>

app/views/thres/new.html.erb
<%= form_for @thre, url: {action: :create} do |f| %>
    <%= f.label :title, 'タイトル' %>
    <%= f.text_area :title%>
    <%= f.submit '追加' %>
<%end%>

app/views/thres/show.html.erb
<div class = thred >
<% thre = Thre.find_by(id: params[:id]) %>
<h1><%= thre.title %></h1>

<h2>レス一覧</h2>

<% Response.where(user_id: current_user.uid).each do |res| %>
    <p>
    <%= res.id %>.
    投稿者：
    <%= User.find_by(uid: res.user_id).name %>
    <%= res.tdate.strftime("%Y/%m/%d %X") %>
    <%= link_to '表示', response_path(res.id) %>
    <%= link_to '削除', response_path(res.id), method: :delete %><br>
    <%= res.message %><br>
    <% if res.image.attached? %>
           <%= image_tag res.image, width: '10%', height: '10%'  %><br>
    <% else %>
           <%= image_tag 'n.png', width: '0px', height: '0px' %><br>
    <% end %>
    評価：
    <%= link_to '👍', likes_path(res_id: res.id), method: :post %>
    <% like_n = Like.where(response_id: res.id).count %>
    <% if like_n == 0 %>
        <%= like_n %>
    <% elsif like_n >= 10 %>
        <h class="good_count_2">+<%= like_n %></h>
    <% else %>
        <h class="good_count">+<%= like_n %></h>
    <% end %>
    　
    <%= link_to '👎', dislikes_path(res_id: res.id), method: :post %>
    <% dislike_n = Dislike.where(response_id: res.id).count %>
    <% if dislike_n == 0 %>
        <%= dislike_n %>
    <% elsif dislike_n >= 10 %>
        <h class="bad_count_2">－<%= dislike_n %></h>
    <% else %>
        <h class="bad_count">－<%= dislike_n %></h>
    <% end %>
    </p>
<% end %>
</div>

<p><%= link_to '投稿する', new_response_path %></p>
<p><%= link_to 'スレッド一覧に戻る', thres_path %></p>
<p><%= link_to 'トップに戻る', top_main_path %></p>

app/views/top/login.html.erb
<div class = log> 
    <h1>ログイン</h1>
    <p></p>
    <%= form_tag '/top/login', method: :post do %>
        <h4>ユーザーIDとパスワードを入力してください</h4>
        <p>
            <%= label_tag :uid, 'ユーザーID' %><br>
            <%= text_field_tag :uid %>
        </p>
        <p>
            <%= label_tag :pass, 'パスワード' %><br>
            <%= password_field_tag :pass %>
        </p>
        <p><%= submit_tag 'ログイン' %></p>
    <% end %>
    <p></p>
    <%= link_to 'パスワード情報', users_path %>
</div>

app/views/top/main.html.erb
<div class = mai>
    <h1>Kinboardへようこそ!</h1>
    <h4>このサイトは、気軽に誰でもつぶやける掲示板サイトです</h4>
    
    <%= @db_pass %>
    
    <% if current_user %>
        <h class="current_user"><%= current_user.name %></h>
        でログイン中です。<br>
        <p><%= link_to 'アカウント情報', users_profile_path %></p>
        <p><%= link_to 'ログアウト', top_logout_path %></p>
    <% else %>
        <p><%= link_to 'ログイン', top_login_path %></p>
    <% end %>
    
        <p>
            <%= link_to 'スレ一覧', thres_path %>
            <%= link_to 'ログイン', top_login_path %>
            <%= link_to 'ログアウト', top_logout_path %>
            <%= link_to 'パスワード情報', users_path %>
        </p>
</div>

app/views/users/edit.html.erb
<%= form_for @user, url: {action: :update} do |f| %>
    <%= f.label :name, 'ニックネーム' %>
    <%= f.text_area :name%>
    <%= f.submit '更新' %>
<%end%>

app/views/users/index.html.erb
<h1>アカウント情報</h1>
<% @users.each do |my| %>
   <p> 
       id: <%= my.uid %>
       pass: <%= my.pass %>
       ニックネーム: <%= my.name %>
       <%= link_to '削除', user_path(my.id), method: :delete %>
       <%= link_to '編集', edit_user_path(my.id) %>
    </p>
<% end %>

<p><%= link_to '新規追加', new_user_path %></p>
<p><%= link_to 'トップに戻る', top_main_path %></p>

app/views/users/new.html.erb
<% if @user.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
    <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
</ul>
<% end %>

<%= form_for @user , url: {action: :create} do |f| %>
    <%= f.label :uid, 'id' %>
    <%= f.text_area :uid %>
    <%= f.label :pass, 'パスワード' %>
    <%= f.text_area :pass%>
    <%= f.label :name, 'ニックネーム' %>
    <%= f.text_area :name%>
    <%= f.submit '追加' %>
<%end%>

app/views/users/profile.html.erb
<h1>プロフィール情報</h1>
<h2 class="info">基本情報</h2>
    <% user = User.find_by(uid: current_user) %>
        idが
        <%= current_user.uid %>
        のユーザー情報です。
        <table initialTab="table_info" %>
            <tr>
                <th>ニックネーム：</th>
                <td><%= current_user.name %></td>
            </tr>
            <tr>
                <th>ユーザーID：</th>
                <td><%= current_user.uid %></td>
            </tr>
            <tr>
                <th>登録日時：</th>
                <td><%= current_user.created_at.strftime('%Y年%m月%d日') %></td>
            </tr>
            <tr>
                <th>通算高評価：</th>
                <td>てすと</td>
            </tr>
            <tr>
                <th>通算低評価：</th>
                <td>てすつ</td>
            </tr>
        </table>

<h2 class="namechange">ニックネーム変更</h2>